<?php

namespace AppBundle\Repository;

/**
 * EthAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockchainAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
