<?php

namespace AppBundle\Repository;

/**
 * CryptoCurrencyHistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CryptoCurrencyHistoricRepository extends \Doctrine\ORM\EntityRepository
{
}
