<?php

namespace AppBundle\Repository;

/**
 * CurrencyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
