<?php

namespace AppBundle\Repository;

/**
 * CurrencySellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencySellRepository extends \Doctrine\ORM\EntityRepository
{
}
