<?php

namespace AppBundle\Repository;

/**
 * EbaySellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EbaySellRepository extends \Doctrine\ORM\EntityRepository
{
}
