<?php

namespace AppBundle\Repository;

/**
 * GpuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpuRepository extends \Doctrine\ORM\EntityRepository
{
}
