<?php

namespace AppBundle\Repository;

/**
 * HoldingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoldingRepository extends \Doctrine\ORM\EntityRepository
{
}
