<?php

namespace AppBundle\Repository;

/**
 * HoldingCryptoAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoldingCryptoAmountRepository extends \Doctrine\ORM\EntityRepository
{
}
