<?php

namespace AppBundle\Repository;

/**
 * MinerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinerRepository extends \Doctrine\ORM\EntityRepository
{
}
