<?php

namespace AppBundle\Repository\Alert;

/**
 * TransactionAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
