<?php

namespace AppBundle\Repository\Alert;

/**
 * TwitterAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
